runtime: python
env: flex
entrypoint: gunicorn -b :$PORT app:app
runtime_config:
    python_version: 3.7
env_variables:
    CLOUD_STORAGE_BUCKET: audio_storage_cloud
manual_scaling:
    instances: 6
